# Copyright (C) 2008 Free Software Foundation, Inc.
# This file is part of the GNU C Library.

# The GNU C Library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.

# The GNU C Library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with the GNU C Library; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307 USA.

# Makefile for rtld_db library subdirectory of GNU C Library.

subdir          := rtld_db

extra-libs = librtld_db
extra-libs-others := $(extra-libs)

headers         := rtld_db.h

librtld_db-routines = rd_init rd_new rd_reset rd_delete rd_loadobj_iter \
    rd_log rd_get_dyns rd_event_enable rd_event_addr rd_event_getmsg

include ../Makeconfig

include ../Rules
